# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(711, 787)
        self.addPlanGB = QtWidgets.QGroupBox(Admin)
        self.addPlanGB.setGeometry(QtCore.QRect(20, 10, 391, 321))
        self.addPlanGB.setObjectName("addPlanGB")
        self.splitter_6 = QtWidgets.QSplitter(self.addPlanGB)
        self.splitter_6.setGeometry(QtCore.QRect(10, 20, 371, 291))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtWidgets.QSplitter(self.splitter_6)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.originLabel = QtWidgets.QLabel(self.splitter)
        self.originLabel.setObjectName("originLabel")
        self.originCombo = QtWidgets.QComboBox(self.splitter)
        self.originCombo.setObjectName("originCombo")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.destinationLabel = QtWidgets.QLabel(self.splitter_2)
        self.destinationLabel.setObjectName("destinationLabel")
        self.destCombo = QtWidgets.QComboBox(self.splitter_2)
        self.destCombo.setObjectName("destCombo")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.busLabel = QtWidgets.QLabel(self.splitter_3)
        self.busLabel.setObjectName("busLabel")
        self.busCombo = QtWidgets.QComboBox(self.splitter_3)
        self.busCombo.setObjectName("busCombo")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.dptLabel = QtWidgets.QLabel(self.splitter_4)
        self.dptLabel.setObjectName("dptLabel")
        self.dptDatePicker = QtWidgets.QDateTimeEdit(self.splitter_4)
        self.dptDatePicker.setObjectName("dptDatePicker")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.arvLabel = QtWidgets.QLabel(self.splitter_5)
        self.arvLabel.setObjectName("arvLabel")
        self.arvDatePicker = QtWidgets.QDateTimeEdit(self.splitter_5)
        self.arvDatePicker.setObjectName("arvDatePicker")
        self.addPlanBtn = QtWidgets.QPushButton(self.splitter_6)
        self.addPlanBtn.setObjectName("addPlanBtn")
        self.addCityGB = QtWidgets.QGroupBox(Admin)
        self.addCityGB.setGeometry(QtCore.QRect(420, 10, 281, 101))
        self.addCityGB.setObjectName("addCityGB")
        self.splitter_8 = QtWidgets.QSplitter(self.addCityGB)
        self.splitter_8.setGeometry(QtCore.QRect(10, 20, 251, 71))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.cityNameLabel = QtWidgets.QLabel(self.splitter_7)
        self.cityNameLabel.setObjectName("cityNameLabel")
        self.cityNameLineEdit = QtWidgets.QLineEdit(self.splitter_7)
        self.cityNameLineEdit.setObjectName("cityNameLineEdit")
        self.addCityButton = QtWidgets.QPushButton(self.splitter_8)
        self.addCityButton.setObjectName("addCityButton")
        self.addBusGB = QtWidgets.QGroupBox(Admin)
        self.addBusGB.setGeometry(QtCore.QRect(420, 110, 281, 141))
        self.addBusGB.setObjectName("addBusGB")
        self.splitter_11 = QtWidgets.QSplitter(self.addBusGB)
        self.splitter_11.setGeometry(QtCore.QRect(10, 20, 261, 111))
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.driverNameLabel = QtWidgets.QLabel(self.splitter_9)
        self.driverNameLabel.setObjectName("driverNameLabel")
        self.driverNameLineEdit = QtWidgets.QLineEdit(self.splitter_9)
        self.driverNameLineEdit.setObjectName("driverNameLineEdit")
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_11)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.capacityLabel = QtWidgets.QLabel(self.splitter_10)
        self.capacityLabel.setObjectName("capacityLabel")
        self.capacitySpin = QtWidgets.QSpinBox(self.splitter_10)
        self.capacitySpin.setMinimum(20)
        self.capacitySpin.setMaximum(50)
        self.capacitySpin.setSingleStep(5)
        self.capacitySpin.setObjectName("capacitySpin")
        self.addBusBtn = QtWidgets.QPushButton(self.splitter_11)
        self.addBusBtn.setObjectName("addBusBtn")
        self.planGB = QtWidgets.QGroupBox(Admin)
        self.planGB.setGeometry(QtCore.QRect(20, 600, 681, 181))
        self.planGB.setObjectName("planGB")
        self.splitter_12 = QtWidgets.QSplitter(self.planGB)
        self.splitter_12.setGeometry(QtCore.QRect(10, 20, 661, 151))
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.planTable = QtWidgets.QTableWidget(self.splitter_12)
        self.planTable.setObjectName("planTable")
        self.planTable.setColumnCount(0)
        self.planTable.setRowCount(0)
        self.deletePlanBtn = QtWidgets.QPushButton(self.splitter_12)
        self.deletePlanBtn.setObjectName("deletePlanBtn")
        self.cityGB = QtWidgets.QGroupBox(Admin)
        self.cityGB.setGeometry(QtCore.QRect(420, 260, 281, 161))
        self.cityGB.setObjectName("cityGB")
        self.splitter_13 = QtWidgets.QSplitter(self.cityGB)
        self.splitter_13.setGeometry(QtCore.QRect(10, 20, 256, 131))
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.cityTable = QtWidgets.QTableWidget(self.splitter_13)
        self.cityTable.setObjectName("cityTable")
        self.cityTable.setColumnCount(0)
        self.cityTable.setRowCount(0)
        self.deleteCityBtn = QtWidgets.QPushButton(self.splitter_13)
        self.deleteCityBtn.setObjectName("deleteCityBtn")
        self.busGB = QtWidgets.QGroupBox(Admin)
        self.busGB.setGeometry(QtCore.QRect(420, 430, 281, 171))
        self.busGB.setObjectName("busGB")
        self.splitter_14 = QtWidgets.QSplitter(self.busGB)
        self.splitter_14.setGeometry(QtCore.QRect(10, 20, 256, 141))
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName("splitter_14")
        self.busTable = QtWidgets.QTableWidget(self.splitter_14)
        self.busTable.setObjectName("busTable")
        self.busTable.setColumnCount(0)
        self.busTable.setRowCount(0)
        self.deleteBusBtn = QtWidgets.QPushButton(self.splitter_14)
        self.deleteBusBtn.setObjectName("deleteBusBtn")
        self.reserveGB = QtWidgets.QGroupBox(Admin)
        self.reserveGB.setGeometry(QtCore.QRect(20, 340, 391, 261))
        self.reserveGB.setObjectName("reserveGB")
        self.splitter_15 = QtWidgets.QSplitter(self.reserveGB)
        self.splitter_15.setGeometry(QtCore.QRect(10, 20, 371, 231))
        self.splitter_15.setOrientation(QtCore.Qt.Vertical)
        self.splitter_15.setObjectName("splitter_15")
        self.reserveTable = QtWidgets.QTableWidget(self.splitter_15)
        self.reserveTable.setObjectName("reserveTable")
        self.reserveTable.setColumnCount(0)
        self.reserveTable.setRowCount(0)
        self.deleteReservationBtn = QtWidgets.QPushButton(self.splitter_15)
        self.deleteReservationBtn.setObjectName("deleteReservationBtn")

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Admin Panel"))
        self.addPlanGB.setTitle(_translate("Admin", "Add Plan"))
        self.originLabel.setText(_translate("Admin", "Origin:"))
        self.destinationLabel.setText(_translate("Admin", "Destination:"))
        self.busLabel.setText(_translate("Admin", "Available Bus:"))
        self.dptLabel.setText(_translate("Admin", "Departure:"))
        self.arvLabel.setText(_translate("Admin", "Arrival:"))
        self.addPlanBtn.setText(_translate("Admin", "Add Plan"))
        self.addCityGB.setTitle(_translate("Admin", "Add City"))
        self.cityNameLabel.setText(_translate("Admin", "Name:"))
        self.addCityButton.setText(_translate("Admin", "Add City"))
        self.addBusGB.setTitle(_translate("Admin", "Add Bus"))
        self.driverNameLabel.setText(_translate("Admin", "Driver Name:"))
        self.capacityLabel.setText(_translate("Admin", "Capacity:"))
        self.addBusBtn.setText(_translate("Admin", "Add Bus"))
        self.planGB.setTitle(_translate("Admin", "Plans List"))
        self.deletePlanBtn.setText(_translate("Admin", "Delete Plan"))
        self.cityGB.setTitle(_translate("Admin", "City List"))
        self.deleteCityBtn.setText(_translate("Admin", "Delete City"))
        self.busGB.setTitle(_translate("Admin", "Bus List"))
        self.deleteBusBtn.setText(_translate("Admin", "Delete Bus"))
        self.reserveGB.setTitle(_translate("Admin", "Reservation List"))
        self.deleteReservationBtn.setText(_translate("Admin", "Delete Reservation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin = QtWidgets.QWidget()
    ui = Ui_Admin()
    ui.setupUi(Admin)
    Admin.show()
    sys.exit(app.exec_())
